# ST1006 - receiver name should be a reflection of its identity; don't use generic names such as "this" or "self"
checks = ["all", "-ST1006", "-ST1000"]

# TODO: fix these:
# ST1000 - at least one file in a package should have a package comment